package wipro.day3.exceptions;
import java.util.Scanner;

public class TryCatch {
	
	public static void main(String[] args) {
		Scanner obj = new Scanner(System.in);
		
		System.out.println("Enter first number: ");
		int number1 = obj.nextInt();
		
		System.out.println("Enter second number: ");
		int number2 = obj.nextInt();
		
		try {
			int division = x/"abc";
			System.out.println("Division is: "+division);
		}
		catch (ArithmeticException ae) {
			System.out.println("Division by Zero is not possible!");
		}
		
		
	}

}
