package wipro.day3.exceptions;
import java.util.Scanner;

public class TryCatch {
	
	public static void main(String[] args) {
		Scanner obj = new Scanner(System.in);
		
		
		
		try {
			System.out.println("Enter first number: ");
			int number1 = obj.nextInt();
			
			System.out.println("Enter second number: ");
			int number2 = obj.nextInt();
			
			int division = number1/number2;
			System.out.println("Division is: "+division);
		}
		catch (ArithmeticException ae) {
			System.out.println("Division by Zero is not possible!");
		}
		
		
	}

}
