package wipro.day3.exceptions;

public class TryCatch {
	
	public static void main(String[] args) {
		int x = 55;
		
		try {
			int division = x/"abc";
			System.out.println("Division is: "+division);
		}
		catch (ArithmeticException ae) {
			System.out.println("Division by Zero is not possible!");
		}
		
		
	}

}
